version: "3.1"

services:
        mongo_one:
                container_name: mongo1
                image: mongo
                command: mongod --replSet my-mongo-set
                ports:
                        - 27017:27017
                networks:
                        - my-mongo-cluster
                volumes:
                        - ~/home/fnp/Document/mongo/db1:/data/db

        mongo_two:
                container_name: mongo2
                image: mongo
                command: mongod --replSet my-mongo-set
                ports:
                        - 27018:27017
                networks:
                        - my-mongo-cluster
                volumes:
                        - ~/home/fnp/Document/mongo/db2:/data/db

        mongo_three:
                container_name: mongo3
                image: mongo
                command: mongod --replSet my-mongo-set
                ports:
                        - 27019:27017
                networks:
                        - my-mongo-cluster
                volumes:
                        - ~/home/fnp/Document/mongo/db3:/data/db

networks:
        my-mongo-cluster: #leave it there
volumes:
        mongodb_data_volume:
                external: true
